# A  basic script showcasing how to use alias in Elixir

# An alias is a capitalized identifier converted to an atom during compilation
# Math is an alias for Elixir.Math
# Math is a module defined in math.ex
# math.ex was compiled using "elixirc.bat math.ex"  into Elixir.Math.beam
# Elixir.Math.beam - erlang byte code generated by BEAM VM compiler
# This makes Elixir.Math globally accessible
# Modules are always represented as atoms in Erlang VM

alias Elixir.Math, as: Math
IO.puts(Math.square(2))
IO.puts(:"Elixir.Math" == Elixir.Math) # returns true, quote the fullform due to the  "."
